import { WebsiteTemplate } from './types';

export const TEMPLATES: WebsiteTemplate[] = [
  {
    id: 'saas-pulse',
    title: 'PulseAI - Enterprise SaaS & Analytics Platform',
    category: 'AI Startup',
    description: 'High-converting modern SaaS landing page with dark mode aesthetics, interactive pricing calculator, and auth modals.',
    price: 149,
    rating: 4.9,
    reviewsCount: 128,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    tags: ['React', 'Tailwind', 'Next.js', 'Framer Motion'],
    defaultConfig: {
      brandName: 'PulseAI',
      headline: 'Supercharge Your Workflow with Neural Intelligence',
      subheadline: 'The all-in-one AI platform trusted by over 10,000 elite engineering teams worldwide.',
      primaryColor: '#6366f1', // Indigo
      buttonText: 'Start Free Trial',
      heroImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
      feature1Title: 'Instant Predictions',
      feature1Desc: 'Generate robust predictions in milliseconds with our optimized edge models.',
      feature2Title: 'Enterprise Security',
      feature2Desc: 'SOC2 Type II certified with end-to-end military-grade encryption.',
      feature3Title: 'Real-time Sync',
      feature3Desc: 'Keep your entire organization synchronized across all devices effortlessly.',
    },
    codePackageSummary: {
      filesCount: 24,
      languages: ['TypeScript', 'CSS', 'HTML'],
      framework: 'Next.js 15 / React',
      size: '4.8 MB',
    },
  },
  {
    id: 'ecommerce-lux',
    title: 'Aura Luxe - High-End E-Commerce Storefront',
    category: 'E-Commerce',
    description: 'Stunning minimalist storefront designed for luxury apparel, jewelry, and lifestyle brands with cart and checkout flow.',
    price: 199,
    rating: 5.0,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
    tags: ['Shopify Ready', 'Tailwind', 'Cart System', 'Responsive'],
    defaultConfig: {
      brandName: 'AURA LUXE',
      headline: 'Timeless Elegance Crafted for the Modern Icon',
      subheadline: 'Explore our curated collection of artisanal masterpieces and exclusive seasonal drops.',
      primaryColor: '#d4af37', // Gold
      buttonText: 'Shop Collection',
      heroImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
      feature1Title: 'Global Express Delivery',
      feature1Desc: 'Complimentary insured shipping to over 120 countries worldwide.',
      feature2Title: 'Handcrafted Quality',
      feature2Desc: 'Sourced from ethical sustainable ateliers with lifetime warranty.',
      feature3Title: 'VIP Concierge',
      feature3Desc: '24/7 dedicated personal styling and order tracking assistance.',
    },
    codePackageSummary: {
      filesCount: 32,
      languages: ['JavaScript', 'Tailwind CSS', 'React'],
      framework: 'React / Vite',
      size: '6.2 MB',
    },
  },
  {
    id: 'portfolio-nexus',
    title: 'Nexus Creator - 3D Developer & Designer Portfolio',
    category: 'Portfolio',
    description: 'Immersive portfolio template with smooth tilt effects, project showcase modals, and interactive contact form.',
    price: 99,
    rating: 4.8,
    reviewsCount: 215,
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    tags: ['Interactive', 'Smooth Scroll', 'Dark Theme', 'Animations'],
    defaultConfig: {
      brandName: 'ALEX.DEV',
      headline: 'Building Digital Realities That Captivate',
      subheadline: 'Senior Full-Stack Architect & Creative Technologist crafting world-class web experiences.',
      primaryColor: '#ec4899', // Pink
      buttonText: 'View Selected Works',
      heroImage: 'https://images.unsplash.com/photo-1534972195531-d756b9cfa9f2?auto=format&fit=crop&w=800&q=80',
      feature1Title: 'Immersive Motion',
      feature1Desc: 'Fluid physics-based animations that elevate user engagement.',
      feature2Title: 'Performance First',
      feature2Desc: 'Lighthouse 100 optimized with blazing fast asset loading.',
      feature3Title: 'Custom CMS',
      feature3Desc: 'Easily update projects and case studies without touching code.',
    },
    codePackageSummary: {
      filesCount: 18,
      languages: ['TypeScript', 'Tailwind', 'Framer Motion'],
      framework: 'Next.js',
      size: '3.5 MB',
    },
  },
  {
    id: 'realestate-vista',
    title: 'Vista Heights - Luxury Real Estate Portal',
    category: 'Real Estate',
    description: 'Sophisticated property listing platform with interactive map search, virtual tours, and mortgage calculator.',
    price: 249,
    rating: 4.9,
    reviewsCount: 76,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    tags: ['Map Integration', 'Listings', 'Filter Engine', 'Responsive'],
    defaultConfig: {
      brandName: 'VISTA HEIGHTS',
      headline: 'Discover Extraordinary Properties in Prime Locations',
      subheadline: 'Your gateway to architectural masterpieces, penthouses, and private coastal estates.',
      primaryColor: '#0ea5e9', // Sky Blue
      buttonText: 'Explore Properties',
      heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
      feature1Title: 'Verified Listings',
      feature1Desc: 'Direct partnerships with premier developers and elite brokers.',
      feature2Title: 'Virtual 3D Tours',
      feature2Desc: 'Immersive walkthroughs from the comfort of your device.',
      feature3Title: 'Private Valuation',
      feature3Desc: 'Confidential property appraisal and portfolio advisory.',
    },
    codePackageSummary: {
      filesCount: 40,
      languages: ['TypeScript', 'Tailwind', 'Leaflet JS'],
      framework: 'Next.js App Router',
      size: '7.9 MB',
    },
  },
  {
    id: 'crypto-nexus',
    title: 'Aether DEX - Web3 Crypto Exchange & Wallet',
    category: 'Crypto',
    description: 'Futuristic decentralized finance dashboard with live token charts, wallet connection UI, and staking pools.',
    price: 299,
    rating: 4.7,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=1200&q=80',
    tags: ['Web3', 'Charts', 'Dark UI', 'Secure'],
    defaultConfig: {
      brandName: 'AETHER DEX',
      headline: 'The Next Generation of Decentralized Liquidity',
      subheadline: 'Trade digital assets with ultra-low latency, deep liquidity, and sovereign security.',
      primaryColor: '#10b981', // Emerald
      buttonText: 'Launch Exchange',
      heroImage: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?auto=format&fit=crop&w=800&q=80',
      feature1Title: 'Zero Slippage',
      feature1Desc: 'Advanced routing algorithms ensuring best execution prices.',
      feature2Title: 'Non-Custodial',
      feature2Desc: 'Your keys, your crypto. Fully audited smart contracts.',
      feature3Title: 'High Yield Staking',
      feature3Desc: 'Earn up to 24% APY on supported governance tokens.',
    },
    codePackageSummary: {
      filesCount: 35,
      languages: ['TypeScript', 'Ethers.js', 'Tailwind'],
      framework: 'React / Next.js',
      size: '5.4 MB',
    },
  },
  {
    id: 'startup-nexus',
    title: 'ScaleFast - Modern Tech Startup Landing',
    category: 'SaaS',
    description: 'High-octane landing page for modern tech startups with customer testimonials, feature grids, and FAQ accordions.',
    price: 129,
    rating: 4.9,
    reviewsCount: 180,
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    tags: ['Conversion Focused', 'Fast', 'SEO Optimized'],
    defaultConfig: {
      brandName: 'ScaleFast',
      headline: 'Accelerate Growth Without Increasing Headcount',
      subheadline: 'Automate repetitive operations and scale revenue with intelligent growth pipelines.',
      primaryColor: '#8b5cf6', // Violet
      buttonText: 'Book a Demo',
      heroImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
      feature1Title: 'Automated Pipelines',
      feature1Desc: 'Turn prospects into loyal customers on autopilot.',
      feature2Title: 'Advanced Analytics',
      feature2Desc: 'Deep insights into conversion funnels and user retention.',
      feature3Title: '24/7 Support',
      feature3Desc: 'Dedicated success managers to help you hit your milestones.',
    },
    codePackageSummary: {
      filesCount: 20,
      languages: ['React', 'Tailwind', 'JavaScript'],
      framework: 'Next.js',
      size: '3.1 MB',
    },
  },
];
